#!/bin/sh

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid "dark slate grey"
vncconfig -iconic &
# This will bring up ssh-askpass if you define a password-protected SSH key
eval $( ssh-agent -s )
ssh-add &
fbpanel &
exec x-window-manager
eval $( ssh-agent -k )
